### ISSUE TITLE
MFA Error on WSL

### ISSUE THREAD

**Issue by pitgrap** [xeger/awsume-yubikey-plugin#2]
**Describe the bug**
I'm using "awsume" and this plugin in WSL2. ykman is installed in Windows and linked to WSL.
Calling "ykman --version" in the Linus shell works as expected.
The Plugin detects my Yubikey but it fails to send the MFA token to awsume.

**Expected behavior**
It works

**Output**
```
❯ awsume MY_AWS_ACCOUNT
Touch your YubiKey...
Obtained MFA token from YubiKey item: XXX
' at 'tokenCode' failed to satisfy constraint: Member must satisfy regular expression pattern: [\d]*e '123456rors detected: Value '123456
```

**Additional context**
I will open a PR with a simple fix. It's all about line endings "\r\n" vs. "\n".

**Comment by xeger** [comment]
Thank you! Published your fix.
